version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  backend:
    image: cwvo-assignment_backend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        dockermachineip: "192.168.99.100"
    working_dir: /todoapp/backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    image: cwvo-assignment_frontend:latest
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /todoapp/frontend
    command: "yarn start"
    ports:
      - "3000:3000"
    depends_on:
      - backend