version: '3'
services:
  db:
    image: postgres
    #ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/todoapp/backend
    ports:
      - "3001:3000"
    depends_on:
      - db
  frontend:
    image: "node:10"
    user: "node"
    working_dir: /todoapp/frontend
    volumes:
      - ./frontend:/todoapp/frontend
    ports:
      - "3000:3000"
    command: "yarn start"
    depends_on:
      - backend